### ISSUE TITLE
would be nice to also have the man page updated

### ISSUE THREAD

**Issue by aaschmid** [Maelan/xclip-targets#1]
thanks for providing this patched "package"

**Comment by Maelan** [comment]
Hello,

Glad it proved useful to someone else. :-)

The man page is already updated by patch nº 005. It adds the following:

       -t, -target
              specify  a  particular data format using the given target atom.
              With -o the special target atom name "TARGETS" can be used
              to get a list of valid target atoms for this selection.  For more
              information about target atoms refer to ICCCM section 2.6.2

and the example:

       xclip -t text/html index.html

       Middle click in an X application supporting HTML to paste the contents
       of the given file as HTML.

Did you have something more in mind?

**Comment by aaschmid** [comment]
Hi @Maelan, thanks for your quick response. It seems that I got tricked by some cache. Opening a new terminal and the man page in it, showed all the changes you mentioned.
Thanks and sorry,
Andreas

**Comment by Maelan** [comment]
No problem. :-)
